version: '3.9'
services:
  authGo:
    image: sainageswar/kotlang-auth:419c7d4ade971e43392d775396ecea97b3aa0c7e
    env_file:
      - .env
    environment:
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
  socialGo:
    image: sainageswar/kotlang-social:937ae00543c155c2dcb9de529647529ac7dff5c8
    env_file:
      - .env
    environment:
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
      - AUTH_TARGET=authGo:50051
      - NOTIFICATION_TARGET=notificationGo:50051
  notificationGo:
    image: sainageswar/kotlang-notification:a10d77beb468299f9e5a0aaaa53b6c42bed4154a
    env_file:
      - .env
    environment:
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
  localizationGo:
    image: sainageswar/kotlang-localizer:77f159672238305499e2e4c2ca30a80998d75218
    env_file:
      - .env
    environment:
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
  navacharApp:
    image: sainageswar/kotlang-navacharapp:dd7ced9b193c3a524927d0f0d332dddaf11a8f9f
    environment:
      - SOCIAL_TARGET=socialGo:50051
      - DEFAULT_USER_JWT_TOKEN_PROD=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJuYXZhY2hhciIsImp0aSI6Ik9EQTFORGs0TkRNMU1BPT0iLCJzdWIiOiJkZWZhdWx0In0.o98y6FMmkk2Ue0xPHQMWqEFAcBakYvfDVniRx1Aj7Lw
      - DEFAULT_USER_JWT_TOKEN_DEV=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJuZXB0dW5lIiwianRpIjoiT0RBMU5EazRORE0xTUE9PSIsInN1YiI6ImRlZmF1bHQifQ.-Y3SNYj1tf4K5gD0RnsFswUkzmeGVC9LLwO0jf4rQ-4
  nginx:
    image: nginx:1.19.6
    ports:
      - "50051:50051"
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - authGo
      - socialGo
      - localizationGo
      - navacharApp
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
