version: '3.9'
services:
  authGo:
    image: sainageswar/kotlang-auth:2c68699261f985b1d12da42637a0c4bcaf6e9c7f
    environment:
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
  socialGo:
    image: sainageswar/kotlang-social:62868f986b6208789b0853359f26d39025b9d1e1
    environment:
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
      - AUTH_TARGET=authGo:50051
  nginx:
    image: nginx:1.19.6
    ports:
      - "50051:50051"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - authGo
      - socialGo
