version: '3.9'
services:
  authGo:
    image: navachar/kotlang-auth:0c238fb70d12a57e70231dbcb7fc790c0fa1d60f
    env_file:
      - .env
    environment:
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
  socialGo:
    image: navachar/kotlang-social:84565ed510a58f8d2d590eebe9854f3e8b9ac352
    env_file:
      - .env
    environment:
      - AUTH_TARGET=authGo:50051
      - NOTIFICATION_TARGET=notificationGo:50051
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}

  notificationGo:
    image: navachar/kotlang-notification:d6d73999b2f7c466a01d0f3798bf3e2899c5a1b5
    env_file:
      - .env
    environment:
      - AUTH_TARGET=authGo:50051
      - SOCIAL_TARGET=socialGo:50051
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}

  localizationGo:
    image: navachar/kotlang-localizer:d48df507f96ccc3d83ff70961b004dbe85f05c92
    env_file:
      - .env
    environment:
      - AUTH_TARGET=authGo:50051
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
  navacharApp:
    image: navachar/kotlang-navacharapp:73c257bae9fff1eb421b6fbe13cf17897c46cdd0
    environment:
      - SOCIAL_TARGET=socialGo:50051
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
  navacharAdminPanel:
    image: navachar/kotlang-navachar-admin-panel:6ac12157f7b98dc98fa5dc1ac7ef539b381fbcec
  navacharWebsite:
    image: navachar/kotlang-navachar-website:8065708b568f254f6df29a0b5d7575165ad98ea0
  nginx:
    image: nginx:1.19.6
    ports:
      - "50051:50051"
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - authGo
      - socialGo
      - localizationGo
      - navacharApp
      - navacharWebsite
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
