version: '3.9'
services:
  authGo:
    image: sainageswar/kotlang-auth:18e495d4b0acafd333b5c9107f153c739a265e14
    environment:
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
  socialGo:
    image: sainageswar/kotlang-social:9e0769a88aa43fff9324f6ce996cab4ec3473583
    environment:
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
      - AUTH_TARGET=authGo:50051
  localizationGo:
    image: sainageswar/kotlang-localizer:85833b045f0c079ee5c4b19761ace18ae9015134
    environment:
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
  navacharApp:
    image: sainageswar/kotlang-navacharapp:46cfd7168c3a6447f5babf924fa4d66f65e843fe
  nginx:
    image: nginx:1.19.6
    ports:
      - "50051:50051"
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - authGo
      - socialGo
      - localizationGo
      - navacharApp
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
